# Generated by Django 5.0.6 on 2025-05-22 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'carrito',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id_comprobante', models.AutoField(primary_key=True, serialize=False)),
                ('formato', models.CharField(max_length=20)),
                ('fecha_emision', models.DateField()),
            ],
            options={
                'db_table': 'comprobante',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('direccion_entrega', models.CharField(max_length=50)),
                ('fecha_estimada', models.DateField()),
            ],
            options={
                'db_table': 'entrega',
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'genero',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marca',
            },
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id_metodo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'metodo_pago',
            },
        ),
        migrations.CreateModel(
            name='PlanEntrenamiento',
            fields=[
                ('id_plan', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=50)),
                ('duracion_semana', models.IntegerField()),
                ('nivel', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'plan_entrenamiento',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_proveedor', models.CharField(max_length=20)),
                ('rut_proveedor', models.CharField(max_length=12)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=30)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
            },
        ),
        migrations.CreateModel(
            name='DetalleCarrito',
            fields=[
                ('id_detalle_carrito', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.carrito')),
            ],
            options={
                'db_table': 'detalle_carrito',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_detalle_carrito',
            field=models.ForeignKey(blank=True, db_column='id_detalle_carrito', null=True, on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.detallecarrito'),
        ),
        migrations.CreateModel(
            name='DetallePlan',
            fields=[
                ('id_detalle_plan', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.categoria')),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.planentrenamiento')),
            ],
            options={
                'db_table': 'detalle_plan',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.CharField(max_length=100)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.categoria')),
                ('id_marca', models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.marca')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='DetalleProducto',
            fields=[
                ('id_detalle_producto', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.IntegerField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.categoria')),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.planentrenamiento')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.producto')),
            ],
            options={
                'db_table': 'detalle_producto',
            },
        ),
        migrations.AddField(
            model_name='detallecarrito',
            name='id_producto',
            field=models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.producto'),
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('id_region', models.ForeignKey(db_column='id_region', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.region')),
            ],
            options={
                'db_table': 'comuna',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id_tipo_documento', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('id_comprobante', models.ForeignKey(db_column='id_comprobante', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.comprobante')),
            ],
            options={
                'db_table': 'tipo_documento',
            },
        ),
        migrations.CreateModel(
            name='TipoEntrega',
            fields=[
                ('id_tipo_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
                ('id_entrega', models.ForeignKey(db_column='id_entrega', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.entrega')),
            ],
            options={
                'db_table': 'tipo_entrega',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=12)),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('correo', models.EmailField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('tel_emergencia', models.CharField(blank=True, max_length=15, null=True)),
                ('contrasena', models.CharField(max_length=128)),
                ('direccion', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('administrador', 'Administrador'), ('entrenador', 'Entrenador'), ('cliente', 'Cliente'), ('vendedor', 'Vendedor')], default='cliente', max_length=20)),
                ('id_comuna', models.ForeignKey(db_column='id_comuna', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.comuna')),
                ('id_genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.genero')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('estado', models.CharField(max_length=20)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.usuario')),
            ],
            options={
                'db_table': 'reserva',
            },
        ),
        migrations.CreateModel(
            name='ComentarioProdAten',
            fields=[
                ('id_comentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=100)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.usuario')),
            ],
            options={
                'db_table': 'comentario_prod_aten',
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.usuario'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(max_length=20)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('id_carrito', models.OneToOneField(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.carrito')),
                ('id_entrega', models.OneToOneField(db_column='id_entrega', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.entrega')),
            ],
            options={
                'db_table': 'venta',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('en_curso', 'En curso'), ('procesando', 'Procesando'), ('enviado', 'Enviado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='en_curso', max_length=20)),
                ('observacion', models.CharField(blank=True, max_length=200, null=True)),
                ('direccion_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_entrega', models.CharField(blank=True, max_length=50, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('carrito', models.OneToOneField(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.carrito')),
                ('usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.usuario')),
                ('venta', models.OneToOneField(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.venta')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('metodo_pago', models.ForeignKey(db_column='id_metodo_pago', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.metodopago')),
                ('venta', models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.venta')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.AddField(
            model_name='metodopago',
            name='id_venta',
            field=models.ForeignKey(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.venta'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='id_venta',
            field=models.OneToOneField(db_column='id_venta', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.venta'),
        ),
        migrations.CreateModel(
            name='CarritoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_carrito', models.ForeignKey(db_column='id_carrito', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.carrito')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.producto')),
            ],
            options={
                'db_table': 'carrito_producto',
                'unique_together': {('id_carrito', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='ProveedorProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.producto')),
                ('id_proveedor', models.ForeignKey(db_column='id_proveedor', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.proveedor')),
            ],
            options={
                'db_table': 'proveedor_producto',
                'unique_together': {('id_proveedor', 'id_producto')},
            },
        ),
        migrations.CreateModel(
            name='SeguimientoEntrega',
            fields=[
                ('id_seguimiento', models.AutoField(primary_key=True, serialize=False)),
                ('estado_envio', models.CharField(max_length=20)),
                ('fecha_actualizacion', models.DateField()),
                ('id_entrega', models.ForeignKey(db_column='id_entrega', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.entrega')),
            ],
            options={
                'db_table': 'seguimiento_entrega',
                'unique_together': {('id_entrega',)},
            },
        ),
        migrations.CreateModel(
            name='EntrenadorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_plan', models.ForeignKey(db_column='id_plan', on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.planentrenamiento')),
                ('id_entrenador', models.ForeignKey(db_column='id_entrenador', limit_choices_to={'tipo_usuario': 'entrenador'}, on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.usuario')),
            ],
            options={
                'db_table': 'entrenador_plan',
                'unique_together': {('id_entrenador', 'id_plan')},
            },
        ),
    ]
