# Generated by Django 5.0.6 on 2025-05-26 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportFit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planentrenamiento',
            name='id_entrenador',
            field=models.ForeignKey(blank=True, db_column='id_entrenador', limit_choices_to={'tipo_usuario': 'entrenador'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='SportFit_app.usuario'),
        ),
    ]
