# Generated by Django 5.0.6 on 2025-05-26 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SportFit_app', '0002_planentrenamiento_id_entrenador'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id_entrenador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='SportFit_app.usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SportFit_app.planentrenamiento'),
        ),
    ]
