# Generated by Django 5.0.6 on 2025-05-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SportFit_app', '0003_usuario_id_entrenador_usuario_id_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='id_detalle_carrito',
        ),
    ]
